<div class="st-container">
    <div class="st-pusher" id="content"> 
        <div class="st-content"> 

            <div class="cover profile">
                <div class="wrapper">
                    <div class="image">
                        <img src="<?= $this->basePath() . '/img/background.jpg' ?>" alt="people" />
                    </div> 
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#">Mike Savegnago</a></div>
                    <ul class="cover-nav">
                        <li><a href="/application/index/layout"><i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li><a href="/application/index/sobre"><i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li class="active"><a href="/application/eventos"><i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li><a href="/application/imagens/layout"><i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                    </ul>
                </div>
            </div> 

            <div class="row">
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Eventos
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-2">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="/application/eventos/evento" class="h5">Festa da paula</a>
                                            <div class="text-muted">
                                                <small><i class="fa fa-calendar"></i> 24/10/2015</small>
                                            </div>
                                        </div>
                                        <a href="/application/eventos/evento">
                                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="/application/eventos/evento">1 semana</a></li>
                                            <li><i class="fa fa-users fa-fw"></i> <a href="/application/eventos/evento"> 2 Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-plus"></i> Criar Evento
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">
                                <form action="/application/eventos/save" method="post" enctype="multipart/form-data">
                                <div class="col-md-6">
                                    <input type="hidden" class="form-control" name="id" id="id">
                                    
                                    <input type="text" class="form-control" name="titulo" id="titulo" placeholder="Título">
                                    <br>
                                    <input type="text" class="form-control" name="descricao" id="descricao" placeholder="Descricao">
                                    <br>
                                    <input type="text" class="form-control" name="data" id="data" placeholder="Data do evento">
                                </div>
                                <div class="col-md-6">
                                    <h3>Escolha a capa</h3>
                                     <a href="#"><input type="file" name="capa" enctype="multipart/form-data"  id="capa" class="fa fa-photo"> </a>
                                </div>
                                    <input type="submit" class="btn btn-primary" value="Criar" style="float: right">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>