<div class="st-container"> 
    <div class="navbar navbar-main navbar-primary navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav"> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#sidebar-chat" data-toggle="sidebar-menu" class="toggle pull-right visible-xs"><i class="fa fa-comments"></i></a>
                <a class="navbar-brand" href="index.html">Prime</a>
            </div>

            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav"> 
                    <li>
                        <a href="#">Página inicial</a>
                    </li>
                    <form class="navbar-form navbar-left hidden-xs" role="search">
                        <div class="search-2">
                            <div class="input-group">
                                <input type="text" class="form-control form-control-w-150" placeholder="Pesquisar ..">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                        </div>
                    </form>
                </ul>
                <ul class="nav navbar-nav  navbar-right ">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle user" data-toggle="dropdown">
                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="Bill" class="img-circle" width="40" /> Mike <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="user-private-profile.html">Perfil</a></li>
                            <li><a href="login.html">Logout</a></li>
                        </ul>
                    </li>

                </ul>
            </div> 
        </div>
    </div>  
    <div class="st-pusher" id="content"> 
        <div class="st-content"> 

            <div class="cover profile">
                <div class="wrapper">
                    <div class="image">
                        <img src="<?= $this->basePath() . '/img/background.jpg' ?>" alt="people" />
                    </div> 
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#">Mike Savegnago</a></div>
                    <ul class="cover-nav">
                        <li><a href="/application/index/layout"><i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li><a href="/application/index/sobre"><i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li class="active"><a href="/application/eventos"><i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li><a href="/application/imagens/layout"><i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                    </ul>
                </div>
            </div> 

            <div class="row">
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Eventos
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-2">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="/application/eventos/evento" class="h5">Festa da paula</a>
                                            <div class="text-muted">
                                                <small><i class="fa fa-calendar"></i> 24/10/2015</small>
                                            </div>
                                        </div>
                                        <a href="/application/eventos/evento">
                                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="/application/eventos/evento">1 semana</a></li>
                                            <li><i class="fa fa-users fa-fw"></i> <a href="/application/eventos/evento"> 2 Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-plus"></i> Criar Evento
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post">
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="titulo" id="titulo" placeholder="Descrição">
                                    <br>
                                    <input type="text" class="form-control" name="data" id="data" placeholder="Data do evento">
                                </div>
                                <div class="col-md-6">
                                    <h3>Escolha a capa</h3>
                                    <input type="file" name="capa">
                                </div>
                                    <input type="submit" class="btn btn-primary" value="Criar" style="float: right">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>