<?php $usuario = $this->session()->offsetGet('usuario'); ?>
<div class="st-container">
    <div class="st-pusher" id="content">
        <div class="st-content">

            <div class="cover profile">
                <div class="wrapper">
                        <img src="<?= $this->basePath() . $perfil->getCapa(); ?>" alt="people" />
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . $perfil->getFoto(); ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#"><?php echo $perfil->getNome(); ?></a></div>
                    <ul class="cover-nav">
                        <li><a href="/application/index/layout">
                            <i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li><a href="/application/index/sobre/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li class="active"><a href="/application/eventos/index/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li><a href="/application/imagens/layout/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">

                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Meus eventos
                        </div>

                        <?php foreach($eventos as $evento) { ?>

                        <div class="panel-body">

                            <div class="row">

                                <div class="col-md-2">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>" class="h5"><?php echo $evento->getTitulo(); ?></a>
                                            
                                        </div>
                                        <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>">
                                            <img src="<?php echo $evento->getCapa(); ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>">
                                                <?php
                                                 echo $evento->getDataEvento()->format('d/m/Y');
                                                ?>
                                                </a></li>
                                            <li><i class="fa fa-users fa-fw"></i> <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>"> 2 Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div class="col-md-12">

                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Eventos que participo
                        </div>

                        <?php foreach($todos_eventos as $evento) { ?>

                        <div class="panel-body">

                            <div class="row">

                                <div class="col-md-2">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>" class="h5">
                                                <?php echo $evento->getTitulo(); ?></a>
                                        </div>
                                        <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>">
                                            <img src="<?php echo $evento->getCapa(); ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>">
                                                <?php
                                                 echo $evento->getDataEvento()->format('d/m/Y');
                                                ?>
                                                </a></li>
                                            <li><i class="fa fa-users fa-fw"></i> 
                                                <a href="/application/eventos/evento/id/<?php echo $evento->getId();?>/perfil/<?php echo $perfil->getId(); ?>"> 
                                                <?=count($evento->getPerfil())?> Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>


                <div class="col-md-12">

                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-plus"></i> Criar Evento
                        </div>

                        <div class="panel-body">
                            <div class="row">
                                <form action="/application/eventos/save" method="post" enctype="multipart/form-data">
                                <div class="col-md-6">
                                    <input type="hidden" class="form-control" name="perfil" id="perfil" value="<?php echo $usuario->getId();?>">
                                    <input type="text" class="form-control" name="titulo" id="titulo" placeholder="Título">
                                    <br>
                                    <input type="text" class="form-control" name="descricao" id="descricao" placeholder="Descricao">
                                    <br>
                                    <input type="text" class="form-control date" name="dataEvento" id="dataEvento" placeholder="Data do evento">
                                </div>
                                <div class="col-md-6">
                                    <h3>Escolha a capa</h3>
                                     <a href="#"><input type="file" name="capa" enctype="multipart/form-data"  id="capa" class="fa fa-photo"> </a>
                                </div>
                                    <input type="submit" class="btn btn-primary" value="Criar" style="float: right">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>