<div class="panel panel-default">
    <div class="panel-body" style="width: 500px;">
      <?php
        echo $this->form()->openTag($formUfs);
        echo $this->form()->openTag($formEndereco);
        echo $this->form()->openTag($formCidade);
    ?>

        
    <div>
        <?php // echo $formUfs->get('descricao')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php // echo $this->formInput($formUfs->get('descricao')); ?>
    </div> 
    <div>
        <?php echo  $formCidade->get('uf')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php  echo  $this->formInput($formCidade->get('uf')); ?>
    </div> 
    <div>
        <?php  echo $formCidade->get('cidade')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($formCidade->get('cidade')); ?>
    </div> 
    <div>
        <?php  echo $formEndereco->get('rua')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($formEndereco->get('rua')); ?>
    </div>
    <div>
        <?php echo $formEndereco->get('numero')->getLabel();  ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($formEndereco->get('numero'));  ?>
    </div> 
    <br>
    <div>
        <?php  echo $formEndereco->get('bairro')->getLabel();  ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($formEndereco->get('bairro'));  ?>
    </div> 
   
    <br><hr>
    <br>
    <div class="input-group">
        <?php  echo $this->formSubmit($formEndereco->get('submit'));  ?>
    </div> 
    <?php 
        echo $this->form()->closeTag();
    ?>
  </div>
</div>