<?php $usuario = $this->session()->offsetGet('usuario'); ?>
<div class="st-container"> 
    <div class="st-pusher" id="content"> 
        <div class="st-content"> 

            <div class="cover profile">
                <div class="wrapper">
                    <div class="image">
                        <img src="<?=$this->basePath() . '/img/background.jpg'?>" alt="people" />
                    </div> 
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?=$this->basePath() . '/img/user.jpg'?>" alt="people" />
                    </div>
                    <div class="name"><a href="#"><?php echo $usuario->getNome(); ?></a></div>
                    <ul class="cover-nav">
                        <li><a href="/application/index/layout">
                            <i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li ><a href="/application/index/sobre/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li><a href="/application/eventos/index/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li class="active"><a href="/application/imagens/layout/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-photo"></i> Albuns
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-2">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-photo"></i></a>
                                            </div>
                                            <a href="/application/eventos/evento" class="h5">Festa da paula</a>
                                        </div>
                                        <a href="/application/imagens">
                                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="image" class="img-responsive">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-plus"></i> Criar Album
                        </div>
                        
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post">
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="titulo" id="titulo" placeholder="Descrição">
                                </div>
                                    <input type="submit" class="btn btn-primary" value="Criar" style="float: right">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>