<div class="panel panel-default">
    <div class="panel-body" style="width: 500px;">
      <?php
        echo $this->form()->openTag($form);
    ?>
        <?php echo $this->formHidden($form->get('id')); ?>
    <div>
        <?php echo $form->get('nome')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('nome')); ?>
    </div> 
    <div>
        <?php echo $form->get('sobrenome')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('sobrenome')); ?>
    </div> 
    <div>
        <?php echo $form->get('email')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('email')); ?>
    </div> 
    <div>
        <?php echo $form->get('celular')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('celular')); ?>
    </div> 
    <div>
        <?php echo $form->get('senha')->getLabel();  ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('senha'));  ?>
    </div>  
    <div>
        <?php echo $form->get('dataNascimento')->getLabel();  ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('dataNascimento'));  ?>
    </div> 
    <div>
        <?php echo $form->get('sexo')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('sexo')); ?>
    </div> 
    <br><hr>
    <br>
    <div class="input-group">
        <?php echo $this->formSubmit($form->get('submit'));  ?>
    </div> 
    <?php 
        echo $this->form()->closeTag();
    ?>
  </div>
</div>