<div class="panel panel-default">
    <div class="panel-body" style="width: 500px;">
      <?php
        echo $this->form()->openTag($form); 
    ?>   
      <div>
        <?php  echo $form->get('descricao')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php  echo $this->formInput($form->get('descricao')); ?>
    </div>     
    <div>
        <?php  echo $form->get('foto')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php  echo $this->formInput($form->get('foto')); ?>
    </div>     
    <div class="input-group">
        <?php echo $this->formSubmit($form->get('submit'));  ?>
    </div> 

    <?php 
        echo $this->form()->closeTag();
    ?>
  </div>
</div>