<style>
    body{
        color: #fff;
    }
</style>
<div id="mainWrap">
<div id="loggit">
        <h1> Prime</h1>
        <h3>Por favor, faça seu <strong>login</strong> ou <strong>Registre-se</strong></h3>
    
        <form action="/application/login/login" id="logForm" method="post" class="form-horizontal">
                <div class="form-group">
                        <div class="col-xs-12">
                                <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
                                        <input type="text" name="email" class="form-control input-lg" placeholder="E-mail" autocomplete="off">
                                </div>
                        </div>
                </div>
                <div class="form-group">
                        <div class="col-xs-12">
                                <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                        <input type="password" name="senha" class="form-control input-lg" placeholder="Senha" autocomplete="off">
                                </div>
                        </div>
                </div>
                <div class="form-group formSubmit">
                        <div class="col-sm-7">
                            <div class="form-group formNotice">
                                <p class="text-center">Não tem conta? <span>Registre-se</span></p>
                            </div>
                        </div>
                        <div class="col-sm-5 submitWrap">
                                <button type="submit" class="btn btn-primary btn-lg">Login</button>
                        </div>
                </div>
                
        </form>
        <form action="/application/usuarios/save" id="regForm" method="post" class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                            <input type="text" id="nome" name="nome" class="form-control input-lg" required placeholder="Nome" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                            <input type="text" id="data_nasc" name="data_nasc" class="form-control input-lg date" placeholder="Data de Nascimento" autocomplete="off" required>
                        </div>
                    </div>
                </div>    
                <div class="form-group">
                    <div class="col-xs-12">
                        <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                        <div class="alert alert-danger" style="color:#000; background: #f21f0f; font-weight: bold; margin-bottom: 0px;" role="alert">
                                <?php
                                foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                                    echo $msg;
                                }
                                ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
                            <input type="text" id="email" name="email" class="form-control input-lg" placeholder="E-mail" autocomplete="off" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                        <div class="col-xs-12">
                                <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                        <input type="password" id="senha" name="senha" class="form-control input-lg" required placeholder="Senha" autocomplete="off">
                                </div>
                        </div>
                </div>
                <div class="form-group formSubmit">
                        <div class="col-sm-7">
                            <div class="form-group formNotice">
                                <p class="hasAccount text-center">Já possui conta? <span>Faça seu login!</span></p>
                            </div>
                        </div>
                        <div class="col-sm-5 submitWrap">
                                <button type="submit" class="btn btn-success btn-lg">Registre-se</button>
                        </div>
                </div>
        </form>
</div>  

</div>
<script type="text/javascript">
    
        $(document).ready(function() {
                $('.formNotice span').click(function() {
                        $("#logForm").toggle();
                        $("#regForm").toggle();
                });   
        });
</script>
