
<?php $usuario = $this->session()->offsetGet('usuario');
setlocale( LC_ALL, 'pt_BR', 'pt_BR.iso-8859-1', 'pt_BR.utf-8', 'portuguese' );
?>
<div class="st-container">
    <div class="st-pusher" id="content">
        <div class="st-content">


            <div class="cover profile">
                <div class="wrapper">
                        <img src="<?= $this->basePath() . $usuario->getCapa();?>" alt="people" />
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . $usuario->getCapa(); ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#"><?php echo $usuario->getNome(); ?></a></div>
                    <ul class="cover-nav">
                        <li class="active"><a href="/application/index/layout"><i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li><a href="/application/index/sobre/perfil/<?php echo $usuario->getId(); ?>"><i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li><a href="/application/eventos/index/perfil/<?php echo $usuario->getId(); ?>"><i class="fa fa-fw fa-users"></i> Eventos</a></li>
                         <li><a href="/application/imagens/layout/perfil/<?php echo $usuario->getId(); ?>"><i class="fa fa-fw fa-photo"></i> Fotos</a></li>

                    </ul>
                </div>
            </div>
            
            <div class="timeline row" data-toggle="isotope">
                <div class="col-xs-12">
                    <div class="timeline-block">
                        <form action="/application/murais/save" method="post" enctype="multipart/form-data">
                            <div class="panel panel-default share clearfix-xs">
                                <div class="panel-heading panel-heading-gray title" style="color:#666">
                                    O que está acontecendo?
                                </div>
                                <div class="panel-body">
                                    <textarea name="descricao" class="form-control share-text" rows="3" placeholder="Compartilhe algo conosco..."></textarea>
                                </div>
                                <div class="panel-footer share-buttons">
                                    <a href="#"><input type="file" name="foto" enctype="multipart/form-data"  id="foto"> </a>
                                    <button type="submit" class="btn btn-primary btn-xs pull-right display-block" >Post</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-xs-12">
                <div class="media-body">
                    <div class="media-body-wrapper"> 
                        <?php foreach ($murais as $mural) {
                             //var_dump($mural);exit;
                            ?> 
                            <div class="panel panel-default">
                                <div class="media-body">
                                    <div class="media-body-wrapper">
                                        <div class="panel panel-default">

                                            <div class="panel-body">
                                                <div class="media-left">

                                                    <a href="/application/index/sobre/perfil/<?php echo $mural->getPerfil()->getId(); ?>">
                                                        <img src="<?= $this->basePath() . $mural->getPerfil()->getFoto(); ?>" class="media-object foto-usuario">

                                                    </a>
                                                </div>
                                                <div class="media-body">
                                                    <?php if ($mural->getPerfil()->getId() == $usuario->getId()) {?>
                                                    <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                        <a href="#" data-toggle="dropdown" class="toggle-button">
                                                            <i class="fa fa-pencil"></i>
                                                        </a>
                                                        <ul class="dropdown-menu" role="menu">
                                                            <li><a href="/application/murais/delete/id/<?php echo $mural->getId(); ?>">Deletar</a></li>
                                                        </ul>
                                                    </div>
                                                    <?php } ?>
                                                    <a href="/application/index/sobre/perfil/<?php echo $mural->getPerfil()->getId(); ?>" class="comment-author pull-left"><?php echo $mural->getPerfil()->getNome();?></a><br>
                                                    <div class="comment-date"><?php echo strftime( '%A, %d de %B de %Y', strtotime($mural->getData()->format('Y-m-d')) ); ?></div>
                                                    <span><?php echo $mural->getDescricao(); ?><br>
                                                    <?php if ($mural->getFoto()) { ?>
                                                        <img src="<?php echo $this->basePath() . $mural->getFoto(); ?>" class="foto-mural img-thumbnail">
                                                    <?php } ?>
                                                    </span>
                                                </div>

                                            </div>
                                            <div class="view-all-comments">
                                                <a href="/application/likes/save/id/<?php echo $mural->getId(); ?>">
                                                    <i class="fa fa-like"></i> Like
                                                </a>
                                            </div>
                                            <div class="view-all-comments">
                                                <a href="/application/deslikes/save/id/<?php echo $mural->getId(); ?>">
                                                    <i class="fa fa-like"></i> Deslike
                                                </a>
                                            </div>

                                            <ul class="comments">

                                                <?php foreach($comentarios as $comentario) {
                                                    if($comentario->getMural()->getId() == $mural->getId()){
                                                    ?>

                                                <li class="media">
                                                    <div class="media-left">
                                                        <a href="/application/index/sobre/perfil/<?php echo $comentario->getPerfil()->getId(); ?>">
                                                            <img src="<?= $this->basePath() . $comentario->getPerfil()->getFoto(); ?>" class="media-object foto-usuario">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <a href="/application/index/sobre/perfil/<?php echo $comentario->getPerfil()->getId(); ?>" class="comment-author pull-left">
                                                            <?php echo $comentario->getPerfil()->getNome(); ?></a>
                                                        <span><?php echo $comentario->getComentario(); ?></span>
                                                        <div class="comment-date"><?php  echo strftime( '%A, %d de %B de %Y', strtotime($comentario->getData()->format('Y-m-d')) ); ?></div>
                                                    </div>
                                                </li>

                                                    <?php }}?>
                                                <form action="/application/comentarios/save/id/<?php echo $usuario->getId(); ?>" method="post">
                                                    <li class="comment-form">
                                                        <div class="input-group">
                                                            <input type="hidden" id="id" name="id" value="<?php echo $mural->getId();?>" class="form-control">
                                                            <input type="text" id="comentario" name="comentario" class="form-control">

                                                            <span class="input-group-btn">
                                                                <button type="submit" href="#" class="btn btn-default"><i class="fa fa-comment"></i></button>
                                                            </span>
                                                        </div>
                                                    </li>
                                                </form>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>