<?php $usuario = $this->session()->offsetGet('usuario'); ?>
<div class="st-container">  
    <div class="st-pusher" id="content"> 
        <div class="st-content"> 

            <div class="cover profile">
                <div class="wrapper">
                    <div class="image">
                        <img src="<?= $this->basePath() . '/img/background.jpg' ?>" alt="people" />
                    </div> 
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#">Mike Savegnago</a></div>
                    <ul class="cover-nav">

                        <li><a href="/application/index/layout"><i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li class="active"><a href="/application/index/sobre/id/<?php $usuario->getId(); ?>"><i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li><a href="/application/eventos"><i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li><a href="/application/imagens/layout"><i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                        
                    </ul>
                    <ul class="nav navbar navbar-nav navbar-right " style="margin-right: 5px;">
                        <li><a href=""><i class="fa fa-fw fa-plus"></i>Adicionar Contato</a></li>
                    </ul>  
                </div>
            </div> 

            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <a class="btn btn-white btn-xs pull-right" id="editarPerfil"><i class="fa fa-pencil"></i></a>
                            <i class="fa fa-fw fa-info-circle"></i> Informações do perfil
                        </div>
                        <form action="/application/perfis/save" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="id" value="">
                            <div class="panel-body">
                                <ul class="list-unstyled profile-about margin-none">
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Status Relaciomento</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="statusRelacionamento" id="status_relacionemento" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Fotinha</span></div>
                                            <!--                                            <div class="col-sm-8">
                                                                                           <a href="#"><input type="file" name="foto" enctype="multipart/form-data"  id="foto" class="fa fa-photo"> </a>
                                                                                        </div>-->
                                            <div class="panel-footer share-buttons">
                                                <a href="#"><input type="file" name="foto" enctype="multipart/form-data"
                                                                    style="background: #fff; border: #fff 0px solid" 
                                                                    id="foto" class="fa fa-photo"> </a>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Data de nascimento</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="dataNascimento" id="data_nasc" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Onde trabalha</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="ondeTrabalha" id="onde_trabalha" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Profissão</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="profissao" id="profissao" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Formação</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="formacao" id="formacao" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Gênero</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="sexo" id="sexo" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Cidade</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="cidade" id="cidade" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li> 
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">UF</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="uf" id="uf" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li> 
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Rua</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="rua" id="rua" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li> 
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Número</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="numero" id="numero" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li> 
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Bairro</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="bairro" id="bairro" disabled 
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li> 
                                    <!--                                   //comentado pois o email ja vai esta na sessao-->
                                    <!--                                    <li class="padding-v-5">
                                                                           <div class="row">
                                                                               <div class="col-sm-4"><span class="text-muted">E-mail</span></div>
                                                                               <div class="col-sm-8">
                                                                                   <input type="text" name="email" id="email" disabled 
                                                                                          style="background: #fff; border: #fff 0px solid" 
                                                                                          value="...@unochapeco.edu.br" />
                                                                               </div>
                                                                           </div>
                                                                       </li>-->
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Quem Pode Ver</span></div>
                                            <div class="col-sm-8">
                                                <select type="select" name="permissao" id="permissao" disabled 
                                                        style="background: #fff; border: #fff 0px solid" >
                                                    <option value="AMIGOS" selected>Amigos</option>      
                                                    <option value="TODOS" >Todos</option>
                                                </select>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <button type="submit" class="btn btn-primary btn-xs pull-right display-block" href="#">Salvar</button>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-fw fa-photo"></i> Albuns
                        </div>
                        <div class="panel-body">

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Eventos
                        </div>
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-4">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="#" class="h5">Festa da paula</a>
                                            <div class="text-muted">
                                                <small><i class="fa fa-calendar"></i> 24/10/2015</small>
                                            </div>
                                        </div>
                                        <a href="#">
                                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="#">1 semana</a></li>
                                            <li><i class="fa fa-users fa-fw"></i> <a href="#"> 2 Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="media-body">
                            <div class="media-body-wrapper">
                                <div class="panel panel-default">

                                    <div class="panel-body">
                                        <div class="media-left">
                                            <a href="">
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                <a href="#" data-toggle="dropdown" class="toggle-button">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Editar</a></li>
                                                    <li><a href="#">Deletar</a></li>
                                                </ul>
                                            </div>
                                            <a href="" class="comment-author pull-left">Ana P.</a><br>
                                            <div class="comment-date">09 de junho</div>
                                            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis perspiciatis praesentium quaerat repudiandae soluta? Cum doloribus esse et eum facilis impedit officiis omnis optio, placeat, quia quo reprehenderit sunt
                                                velit? Asperiores cumque deserunt eveniet hic reprehenderit sit, ut voluptatum?<br>
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="foto-mural img-thumbnail">
                                            </span>
                                        </div>

                                    </div>
                                    <div class="view-all-comments">
                                        <a href="#">
                                            <i class="fa fa-comments-o"></i> Ver todos
                                        </a>
                                        <span>1 comentário</span>

                                    </div>
                                    <ul class="comments">
                                        <li class="media">
                                            <div class="media-left">
                                                <a href="">
                                                    <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-right dropdown" data-show-hover="li" style="display: block;">
                                                    <a href="#" data-toggle="dropdown" class="toggle-button">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Editar</a></li>
                                                        <li><a href="#">Deletar</a></li>
                                                    </ul>
                                                </div>
                                                <a href="" class="comment-author pull-left">Ana P.</a>
                                                <span>Gostei manolo</span>
                                                <div class="comment-date">09 de junho</div>
                                            </div>
                                        </li>
                                        <li class="comment-form">
                                            <div class="input-group"> 
                                                <input type="text" class="form-control">
                                                <span class="input-group-btn">
                                                    <a href="" class="btn btn-default"><i class="fa fa-comment"></i></a>
                                                </span>

                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="media-body">
                            <div class="media-body-wrapper">
                                <div class="panel panel-default">

                                    <div class="panel-body">
                                        <div class="media-left">
                                            <a href="">
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                <a href="#" data-toggle="dropdown" class="toggle-button">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Editar</a></li>
                                                    <li><a href="#">Deletar</a></li>
                                                </ul>
                                            </div>
                                            <a href="" class="comment-author pull-left">Ana P.</a><br>
                                            <div class="comment-date">09 de junho</div>
                                            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis perspiciatis praesentium quaerat repudiandae soluta? Cum doloribus esse et eum facilis impedit officiis omnis optio, placeat, quia quo reprehenderit sunt
                                                velit? Asperiores cumque deserunt eveniet hic reprehenderit sit, ut voluptatum?<br>
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="foto-mural img-thumbnail">
                                            </span>
                                        </div>

                                    </div>
                                    <div class="view-all-comments">
                                        <a href="#">
                                            <i class="fa fa-comments-o"></i> Ver todos
                                        </a>
                                        <span>1 comentário</span>

                                    </div>
                                    <ul class="comments">
                                        <li class="media">
                                            <div class="media-left">
                                                <a href="">
                                                    <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-right dropdown" data-show-hover="li" style="display: block;">
                                                    <a href="#" data-toggle="dropdown" class="toggle-button">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Editar</a></li>
                                                        <li><a href="#">Deletar</a></li>
                                                    </ul>
                                                </div>
                                                <a href="" class="comment-author pull-left">Ana P.</a>
                                                <span>Gostei manolo</span>
                                                <div class="comment-date">09 de junho</div>
                                            </div>
                                        </li>
                                        <li class="comment-form">
                                            <div class="input-group"> 
                                                <input type="text" class="form-control">
                                                <span class="input-group-btn">
                                                    <a href="" class="btn btn-default"><i class="fa fa-comment"></i></a>
                                                </span>

                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $("#editarPerfil").click(function () {
        $('#rua').removeAttr("disabled");
        $('#rua').attr("style", '');
        $('#rua').attr("class", 'form-control');
        $('#numero').removeAttr("disabled");
        $('#numero').attr("style", '');
        $('#numero').attr("class", 'form-control');
        $('#bairro').removeAttr("disabled");
        $('#bairro').attr("style", '');
        $('#bairro').attr("class", 'form-control');
        $('#uf').removeAttr("disabled");
        $('#uf').attr("style", '');
        $('#uf').attr("class", 'form-control');
        $('#cidade').removeAttr("disabled");
        $('#cidade').attr("style", '');
        $('#cidade').attr("class", 'form-control');
        $('#status_relacionemento').removeAttr("disabled");
        $('#status_relacionemento').attr("style", '');
        $('#status_relacionemento').attr("class", 'form-control');
        $('#profissao').removeAttr("disabled");
        $('#profissao').attr("style", '');
        $('#profissao').attr("class", 'form-control');
        $('#formacao').removeAttr("disabled");
        $('#formacao').attr("style", '');
        $('#formacao').attr("class", 'form-control');
        $('#permissao').removeAttr("disabled");
        $('#permissao').attr("style", '');
        $('#permissao').attr("class", 'form-control');
        $('#data_nasc').removeAttr("disabled");
        $('#data_nasc').attr("style", '');
        $('#data_nasc').attr("class", 'form-control');
        $('#onde_trabalha').removeAttr("disabled");
        $('#onde_trabalha').attr("style", '');
        $('#onde_trabalha').attr("class", 'form-control');
        $('#sexo').removeAttr("disabled");
        $('#sexo').attr("style", '');
        $('#sexo').attr("class", 'form-control');
        $('#email').removeAttr("disabled");
        $('#email').attr("style", '');
        $('#email').attr("class", 'form-control');
        $('#foto').removeAttr("disabled");
        $('#foto').attr("style", '');
        $('#foto').attr("class", 'form-control');
    });
</script>