<div class="st-container"> 
    <div class="navbar navbar-main navbar-primary navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav"> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#sidebar-chat" data-toggle="sidebar-menu" class="toggle pull-right visible-xs"><i class="fa fa-comments"></i></a>
                <a class="navbar-brand" href="index.html">Prime</a>
            </div>

            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav"> 
                    <li>
                        <a href="#">Página inicial</a>
                    </li>
                    <form class="navbar-form navbar-left hidden-xs" role="search">
                        <div class="search-2">
                            <div class="input-group">
                                <input type="text" class="form-control form-control-w-150" placeholder="Pesquisar ..">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                        </div>
                    </form>
                </ul>
                <ul class="nav navbar-nav  navbar-right ">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle user" data-toggle="dropdown">
                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="Bill" class="img-circle" width="40" /> Mike <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="user-private-profile.html">Perfil</a></li>
                            <li><a href="login.html">Logout</a></li>
                        </ul>
                    </li>

                </ul>
            </div> 
        </div>
    </div>  
    <div class="st-pusher" id="content"> 
        <div class="st-content"> 

            <div class="cover profile">
                <div class="wrapper">
                    <div class="image">
                        <img src="<?= $this->basePath() . '/img/background.jpg' ?>" alt="people" />
                    </div> 
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#">Mike Savegnago</a></div>
                    <ul class="cover-nav">

                        <li><a href="/application/index/layout"><i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li class="active"><a href="/application/index/sobre"><i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li><a href="/application/eventos"><i class="fa fa-fw fa-users"></i> Eventos</a></li>

                    </ul>
                </div>
            </div> 

            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <a class="btn btn-white btn-xs pull-right" id="editarPerfil"><i class="fa fa-pencil"></i></a>
                            <i class="fa fa-fw fa-info-circle"></i> Informações do perfil
                        </div>
                        <div class="panel-body">
                            <ul class="list-unstyled profile-about margin-none">
                                <li class="padding-v-5">
                                    <div class="row">
                                        <div class="col-sm-4"><span class="text-muted">Data de nascimento</span></div>
                                        <div class="col-sm-8">
                                            <input type="text" id="data_nasc" disabled 
                                                   style="background: #fff; border: #fff 0px solid" value="22/03/1995" />
                                        </div>
                                    </div>
                                </li>
                                <li class="padding-v-5">
                                    <div class="row">
                                        <div class="col-sm-4"><span class="text-muted">Onde trabalha</span></div>
                                        <div class="col-sm-8">
                                            <input type="text" id="onde_trabalha" disabled 
                                                   style="background: #fff; border: #fff 0px solid" value="uno" />
                                        </div>
                                    </div>
                                </li>
                                <li class="padding-v-5">
                                    <div class="row">
                                        <div class="col-sm-4"><span class="text-muted">Gênero</span></div>
                                        <div class="col-sm-8">
                                            <input type="text" id="sexo" disabled 
                                                   style="background: #fff; border: #fff 0px solid" value="Masculino" />
                                        </div>
                                    </div>
                                </li>
                                <li class="padding-v-5">
                                    <div class="row">
                                        <div class="col-sm-4"><span class="text-muted">Endereço</span></div>
                                        <div class="col-sm-8">
                                            <input type="text" id="endereco" disabled 
                                                   style="background: #fff; border: #fff 0px solid" value="Mariopolis" />
                                        </div>
                                    </div>
                                </li>
                                <li class="padding-v-5">
                                    <div class="row">
                                        <div class="col-sm-4"><span class="text-muted">E-mail</span></div>
                                        <div class="col-sm-8">
                                            <input type="text" id="email" disabled 
                                                   style="background: #fff; border: #fff 0px solid" 
                                                   value="mikesavegnago@unochapeco.edu.br" />
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-fw fa-photo"></i> Albuns
                        </div>
                        <div class="panel-body">

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <i class="fa fa-bookmark"></i> Eventos
                        </div>
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-md-4">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <div class="pull-right">
                                                <a href="#" class="btn btn-success btn-xs"><i class="fa fa-check-circle"></i></a>
                                            </div>
                                            <a href="#" class="h5">Festa da paula</a>
                                            <div class="text-muted">
                                                <small><i class="fa fa-calendar"></i> 24/10/2015</small>
                                            </div>
                                        </div>
                                        <a href="#">
                                            <img src="<?= $this->basePath() . '/img/user.jpg' ?>" alt="image" class="img-responsive">
                                        </a>
                                        <ul class="icon-list icon-list-block">
                                            <li><i class="fa fa-calendar fa-fw"></i> <a href="#">1 semana</a></li>
                                            <li><i class="fa fa-users fa-fw"></i> <a href="#"> 2 Participantes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="media-body">
                            <div class="media-body-wrapper">
                                <div class="panel panel-default">

                                    <div class="panel-body">
                                        <div class="media-left">
                                            <a href="">
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                <a href="#" data-toggle="dropdown" class="toggle-button">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Editar</a></li>
                                                    <li><a href="#">Deletar</a></li>
                                                </ul>
                                            </div>
                                            <a href="" class="comment-author pull-left">Ana P.</a><br>
                                            <div class="comment-date">09 de junho</div>
                                            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis perspiciatis praesentium quaerat repudiandae soluta? Cum doloribus esse et eum facilis impedit officiis omnis optio, placeat, quia quo reprehenderit sunt
                                                velit? Asperiores cumque deserunt eveniet hic reprehenderit sit, ut voluptatum?<br>
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="foto-mural img-thumbnail">
                                            </span>
                                        </div>

                                    </div>
                                    <div class="view-all-comments">
                                        <a href="#">
                                            <i class="fa fa-comments-o"></i> Ver todos
                                        </a>
                                        <span>1 comentário</span>

                                    </div>
                                    <ul class="comments">
                                        <li class="media">
                                            <div class="media-left">
                                                <a href="">
                                                    <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-right dropdown" data-show-hover="li" style="display: block;">
                                                    <a href="#" data-toggle="dropdown" class="toggle-button">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Editar</a></li>
                                                        <li><a href="#">Deletar</a></li>
                                                    </ul>
                                                </div>
                                                <a href="" class="comment-author pull-left">Ana P.</a>
                                                <span>Gostei manolo</span>
                                                <div class="comment-date">09 de junho</div>
                                            </div>
                                        </li>
                                        <li class="comment-form">
                                            <div class="input-group"> 
                                                <input type="text" class="form-control">
                                                <span class="input-group-btn">
                                                    <a href="" class="btn btn-default"><i class="fa fa-comment"></i></a>
                                                </span>

                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="media-body">
                            <div class="media-body-wrapper">
                                <div class="panel panel-default">

                                    <div class="panel-body">
                                        <div class="media-left">
                                            <a href="">
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                <a href="#" data-toggle="dropdown" class="toggle-button">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Editar</a></li>
                                                    <li><a href="#">Deletar</a></li>
                                                </ul>
                                            </div>
                                            <a href="" class="comment-author pull-left">Ana P.</a><br>
                                            <div class="comment-date">09 de junho</div>
                                            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis perspiciatis praesentium quaerat repudiandae soluta? Cum doloribus esse et eum facilis impedit officiis omnis optio, placeat, quia quo reprehenderit sunt
                                                velit? Asperiores cumque deserunt eveniet hic reprehenderit sit, ut voluptatum?<br>
                                                <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="foto-mural img-thumbnail">
                                            </span>
                                        </div>

                                    </div>
                                    <div class="view-all-comments">
                                        <a href="#">
                                            <i class="fa fa-comments-o"></i> Ver todos
                                        </a>
                                        <span>1 comentário</span>

                                    </div>
                                    <ul class="comments">
                                        <li class="media">
                                            <div class="media-left">
                                                <a href="">
                                                    <img src="<?= $this->basePath() . '/img/user.jpg' ?>" class="media-object foto-usuario">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-right dropdown" data-show-hover="li" style="display: block;">
                                                    <a href="#" data-toggle="dropdown" class="toggle-button">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Editar</a></li>
                                                        <li><a href="#">Deletar</a></li>
                                                    </ul>
                                                </div>
                                                <a href="" class="comment-author pull-left">Ana P.</a>
                                                <span>Gostei manolo</span>
                                                <div class="comment-date">09 de junho</div>
                                            </div>
                                        </li>
                                        <li class="comment-form">
                                            <div class="input-group"> 
                                                <input type="text" class="form-control">
                                                <span class="input-group-btn">
                                                    <a href="" class="btn btn-default"><i class="fa fa-comment"></i></a>
                                                </span>

                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $("#editarPerfil").click(function (){ 
        $('#data_nasc').removeAttr("disabled");
        $('#data_nasc').attr("style", '');
        $('#data_nasc').attr("class", 'form-control');
        $('#onde_trabalha').removeAttr("disabled");
        $('#onde_trabalha').attr("style", '');
        $('#onde_trabalha').attr("class", 'form-control');
        $('#sexo').removeAttr("disabled");
        $('#sexo').attr("style", '');
        $('#sexo').attr("class", 'form-control');
        $('#endereco').removeAttr("disabled");
        $('#endereco').attr("style", '');
        $('#endereco').attr("class", 'form-control');
        $('#email').removeAttr("disabled");
        $('#email').attr("style", '');
        $('#email').attr("class", 'form-control');
    });
</script>