<?php $usuario = $this->session()->offsetGet('usuario');
setlocale( LC_ALL, 'pt_BR', 'pt_BR.iso-8859-1', 'pt_BR.utf-8', 'portuguese' );
?>
<div class="st-container">
    <div class="st-pusher" id="content">
        <div class="st-content">

            <div class="cover profile">
                <div class="wrapper">
                        <img src="<?= $this->basePath() . $perfil->getCapa(); ?>" alt="people" />
                </div>
                <div class="cover-info">
                    <div class="avatar">
                        <img src="<?= $this->basePath() . $perfil->getFoto(); ?>" alt="people" />
                    </div>
                    <div class="name"><a href="#"><?php echo $perfil->getNome(); ?></a></div>
                    <ul class="cover-nav">
                        <li><a href="/application/index/layout">
                            <i class="fa fa-fw fa-tasks"></i> Timeline</a></li>
                        <li class="active"><a href="/application/index/sobre/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-user"></i> Perfil</a></li>
                        <li><a href="/application/eventos/index/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-users"></i> Eventos</a></li>
                        <li><a href="/application/imagens/layout/perfil/<?php echo $perfil->getId(); ?>">
                            <i class="fa fa-fw fa-photo"></i> Fotos</a></li>
                    </ul>
                    <?php
                        if ($perfil->getId() != $usuario->getId() && !$amigo){
                    ?>
                    <ul class="nav navbar navbar-nav navbar-right " style="margin-right: 5px;">
                        <li><a href="/application/perfis/adicionar/perfil/<?=$perfil->getid();?>"><i class="fa fa-fw fa-plus"></i>Adicionar Contato</a></li>
                    </ul>
                    <?php } ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-gray">
                            <?php
                                if ($perfil->getid() == $usuario->getId()){
                            ?>
                            <?php } ?>
                            
                            <i class="fa fa-fw fa-info-circle"></i> Informações do perfil
                             <a class="btn btn-white btn-xs pull-right" id="editarPerfil"><i class="fa fa-pencil"></i></a>
                        </div>
                        <form action="/application/perfis/save/id/<?php echo $usuario->getId(); ?>" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="id" value=" <?php echo $usuario->getId(); ?>">
                            <div class="panel-body">
                                <ul class="list-unstyled profile-about margin-none">
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Nome</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="nome" id="nome" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getNome(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">E-mail</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="email" id="email" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getEmail(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5" id="senhaNone" style="display: none">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Senha</span></div>
                                            <div class="col-sm-8">
                                                <input type="password" name="senha" id="senha"
                                                       style="background: #fff; border: #fff 0px solid" value="" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Status Relaciomento</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="statusRelacionamento" id="status_relacionemento" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getStatusRelacionamento(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5" id="fotoPerfil" style="display: none">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Foto Perfil</span></div>
                                            <div class="panel-footer share-buttons">
                                                <a href="#"><input type="file" name="foto_perfil"
                                                                    id="foto_perfil" > </a>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5" id="fotoCapa" style="display: none">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Foto da Capa</span></div>
                                            <div class="panel-footer share-buttons">
                                                <a href="#"><input type="file" name="foto_capa"
                                                                    id="foto_capa" > </a>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Data de nascimento</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="data_nasc" id="data_nasc" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getDataNascimento()->format('d/m/Y'); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Onde trabalha</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="ondeTrabalha" id="onde_trabalha" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getOndeTrabalha(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Celular</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="celular" id="celular" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getCelular(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Profissão</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="profissao" id="profissao" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getProfissao(); ?>"/>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Formação</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="formacao" id="formacao" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getFormacao(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Gênero</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="sexo" id="sexo" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php echo $perfil->getSexo(); ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Cidade</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="cidade" id="cidade" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php  if ($perfil->getEndereco()) {  echo $perfil->getEndereco()->getCidade()->getDescricao(); } ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">UF</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="uf" id="uf" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php if ($perfil->getEndereco()) { echo $perfil->getEndereco()->getUf()->getDescricao(); } ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Rua</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="rua" id="rua" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php if ($perfil->getEndereco()) { echo $perfil->getEndereco()->getRua(); }?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Número</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="numero" id="numero" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php if ($perfil->getEndereco()) { echo $perfil->getEndereco()->getNumero(); }?>"  />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Bairro</span></div>
                                            <div class="col-sm-8">
                                                <input type="text" name="bairro" id="bairro" disabled
                                                       style="background: #fff; border: #fff 0px solid" value="<?php if ($perfil->getEndereco()) { echo $perfil->getEndereco()->getBairro(); } ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="padding-v-5" id="quemVe" style="display: none">
                                        <div class="row">
                                            <div class="col-sm-4"><span class="text-muted">Quem Pode Ver</span></div>
                                            <div class="col-sm-8">
                                                <select type="select" name="permissao" id="permissao"
                                                        style="background: #fff; border: #fff 0px solid" >
                                                    <option value="AMIGOS" selected>Amigos</option>
                                                    <option value="TODOS" >Todos</option>
                                                </select>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <button type="submit" id="salvar" class="btn btn-primary btn-xs pull-right" style="display: none">Salvar</button>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6">
                    <?php foreach ($murais as $mural) { ?>
                            <div class="panel panel-default">
                                <div class="media-body">
                                    <div class="media-body-wrapper">
                                        <div class="panel panel-default">

                                            <div class="panel-body">
                                                <div class="media-left">
                                                    <a href="/application/index/sobre/perfil/<?php echo $mural->getPerfil()->getId(); ?>">
                                                        <img src="<?= $this->basePath() . $mural->getPerfil()->getFoto(); ?>" class="media-object foto-usuario">
                                                    </a>
                                                </div>
                                                <div class="media-body">
                                                    <div class="pull-right dropdown" data-show-hover="li" style="display: block; z-index: 99999;">
                                                        <a href="#" data-toggle="dropdown" class="toggle-button">
                                                            <i class="fa fa-pencil"></i>
                                                        </a>
                                                        <ul class="dropdown-menu" role="menu">
                                                            <li><a href="/application/murais/delete/id/<?php echo $mural->getId(); ?>">Deletar</a></li>
                                                        </ul>
                                                    </div>

                                                    <a href="/application/index/sobre/perfil/<?php echo $mural->getPerfil()->getId(); ?>" class="comment-author pull-left"><?php echo $mural->getPerfil()->getNome();?></a><br>
                                                    <div class="comment-date"><?php echo strftime( '%A, %d de %B de %Y', strtotime($mural->getData()->format('Y-m-d')) ); ?></div>
                                                    <span><?php echo $mural->getDescricao(); ?><br>
                                                        <?php if ($mural->getFoto()){ ?>
                                                        <img src="<?php echo $this->basePath() . $mural->getFoto(); ?>" class="foto-mural img-thumbnail">
                                                        <?php } ?>
                                                    </span>
                                                </div>



                                            </div>
                                            <div class="view-all-comments">
                                               
                                            </div>

                                            <ul class="comments">

                                                <?php foreach($comentarios as $comentario) {
                                                    if($comentario->getMural()->getId() == $mural->getId()){
                                                    ?>

                                                <li class="media">
                                                    <div class="media-left">
                                                        <a href="/application/index/sobre/perfil/<?php echo $comentario->getPerfil()->getId(); ?>">
                                                            <img src="<?= $this->basePath() . $comentario->getPerfil()->getFoto(); ?>" class="media-object foto-usuario">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <div class="pull-right dropdown" data-show-hover="li" style="display: block;">
                                                            <a href="#" data-toggle="dropdown" class="toggle-button">
                                                                <i class="fa fa-pencil"></i>
                                                            </a>
                                                            <ul class="dropdown-menu" role="menu">
                                                                <li><a href="#">Deletar</a></li>
                                                            </ul>
                                                        </div>
                                                        <a href="/application/index/sobre/perfil/<?php echo $comentario->getPerfil()->getId(); ?>" class="comment-author pull-left">
                                                            <?php echo $comentario->getPerfil()->getNome(); ?></a>
                                                        <span><?php echo $comentario->getComentario(); ?></span>
                                                        <div class="comment-date"><?php echo strftime( '%A, %d de %B de %Y', strtotime($comentario->getData()->format('Y-m-d')) ); ?></div>
                                                    </div>
                                                </li>

                                                    <?php }}?>
                                                <form action="/application/comentarios/save/id/<?php echo $usuario->getId(); ?>" method="post">
                                                    <li class="comment-form">
                                                        <div class="input-group">
                                                            <input type="hidden" id="id" name="id" value="<?php echo $mural->getId();?>" class="form-control">
                                                            <input type="text" id="comentario" name="comentario" class="form-control">

                                                            <span class="input-group-btn">
                                                                <button type="submit" href="#" class="btn btn-default"><i class="fa fa-comment"></i></button>
                                                            </span>
                                                        </div>
                                                    </li>
                                                </form>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>

            </div>
        </div>
    </div>
</div>
<script>
    $("#editarPerfil").click(function () {
        $('#rua').removeAttr("disabled");
        $('#rua').attr("style", '');
        $('#rua').attr("class", 'form-control');
        $('#numero').removeAttr("disabled");
        $('#numero').attr("style", '');
        $('#numero').attr("class", 'form-control');
        $('#bairro').removeAttr("disabled");
        $('#bairro').attr("style", '');
        $('#bairro').attr("class", 'form-control');
        $('#uf').removeAttr("disabled");
        $('#uf').attr("style", '');
        $('#uf').attr("class", 'form-control');
        $('#cidade').removeAttr("disabled");
        $('#cidade').attr("style", '');
        $('#cidade').attr("class", 'form-control');
        $('#status_relacionemento').removeAttr("disabled");
        $('#status_relacionemento').attr("style", '');
        $('#status_relacionemento').attr("class", 'form-control');
        $('#profissao').removeAttr("disabled");
        $('#profissao').attr("style", '');
        $('#profissao').attr("class", 'form-control');
        $('#formacao').removeAttr("disabled");
        $('#formacao').attr("style", '');
        $('#formacao').attr("class", 'form-control');
        $('#permissao').removeAttr("disabled");
        $('#permissao').attr("style", '');
        $('#permissao').attr("class", 'form-control');
        $('#data_nasc').removeAttr("disabled");
        $('#data_nasc').attr("style", '');
        $('#data_nasc').attr("class", 'form-control date');
        $('#onde_trabalha').removeAttr("disabled");
        $('#onde_trabalha').attr("style", '');
        $('#onde_trabalha').attr("class", 'form-control');
        $('#sexo').removeAttr("disabled");
        $('#sexo').attr("style", '');
        $('#sexo').attr("class", 'form-control');
        $('#email').removeAttr("disabled");
        $('#email').attr("style", '');
        $('#email').attr("class", 'form-control');
        $('#foto').removeAttr("disabled");
        $('#celular').removeAttr("disabled");
        $('#celular').attr("style", '');
        $('#celular').attr("class", 'form-control');
        $('#nome').removeAttr("disabled");
        $('#nome').attr("style", '');
        $('#nome').attr("class", 'form-control');
        $('#email').removeAttr("disabled");
        $('#email').attr("style", '');
        $('#email').attr("class", 'form-control');
        $('#fotoPerfil').attr("style", '');
        $('#fotoCapa').attr("style", '');
        $('#quemVe').attr("style", '');
        $('#senhaNone').attr("style", '');
        $('#salvar').attr("style", '');
        $('#senha').attr("class", 'form-control');
    });
</script>